import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReownProvider from "@/components/ReownProvider";
import { headers } from "next/headers";
import { Toaster } from "@/components/ui/sonner";

import "@reown/appkit-wallet-button/react";

import "./globals.css";
import Header from "@/containers/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get("cookie");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 dark:from-gray-900 dark:to-gray-800">
          <div className="container mx-auto p-6">
            <ReownProvider cookies={cookies}>
              <Header />
              {children}
              <Toaster />
            </ReownProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
